version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
