services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

    restart: always
    networks:
      - RAG-network

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - RAG-network
    volumes:
      - ./frontend:/app
    restart: always

networks:
  RAG-network:
    driver: bridge